const LOADING = "LOADING";

const SETACCESSTOKEN = "SETACCESSTOKEN";
const SETACCESSTOKENERROR = "SETACCESSTOKENERROR";

const SETNEWRELEASE = "SETNEWRELEASE";
const SETNEWRELEASEERROR = "SETNEWRELEASEERROR";

export {
  LOADING,
  SETACCESSTOKEN,
  SETACCESSTOKENERROR,
  SETNEWRELEASE,
  SETNEWRELEASEERROR
};
