const LOADING = "LOADING";

const SETACCESSTOKEN = "SETACCESSTOKEN";
const SETACCESSTOKENERROR = "SETACCESSTOKENERROR";

const SETNEWRELEASE = "SETNEWRELEASE";
const SETNEWRELEASEERROR = "SETNEWRELEASEERROR";

const SETSEARCHLIST = "SETSEARCHLIST";
const SETSEARCHLISTERROR = "SETSEARCHLISTERROR";
const SETSEARCHNAME = "SETSEARCHNAME";

const SETALBUMDETAIL = "SETALBUMDETAIL";
const SETALBUMDETAILERROR = "SETALBUMDETAILERROR";

export {
  LOADING,
  SETACCESSTOKEN,
  SETACCESSTOKENERROR,
  SETNEWRELEASE,
  SETNEWRELEASEERROR,
  SETSEARCHLIST,
  SETSEARCHLISTERROR,
  SETSEARCHNAME,
  SETALBUMDETAIL,
  SETALBUMDETAILERROR
};
