const LOADING = "LOADING";

const SETACCESSTOKEN = "SETACCESSTOKEN";
const SETACCESSTOKENERROR = "SETACCESSTOKENERROR";

const SETNEWRELEASE = "SETNEWRELEASE";
const SETNEWRELEASEERROR = "SETNEWRELEASEERROR";

const SETSEARCHLIST = "SETSEARCHLIST";
const SETSEARCHLISTERROR = "SETSEARCHLISTERROR";
const SETSEARCHNAME = "SETSEARCHNAME";

const SETALBUMDETAIL = "SETALBUMDETAIL";
const SETALBUMDETAILERROR = "SETALBUMDETAILERROR";
const SETALBUMLIST = "SETALBUMLIST";
const SETALBUMLISTERROR = "SETALBUMLISTERROR";

const SETTRACKLIST = "SETTRACKLIST";
const SETTRACKLISTERROR = "SETTRACKLISTERROR";
const SETTRACKITEM = "SETTRACKITEM";
const SETTRACKITEMERROR = "SETTRACKITEMERROR";

export {
  LOADING,
  SETACCESSTOKEN,
  SETACCESSTOKENERROR,
  SETNEWRELEASE,
  SETNEWRELEASEERROR,
  SETSEARCHLIST,
  SETSEARCHLISTERROR,
  SETSEARCHNAME,
  SETALBUMDETAIL,
  SETALBUMDETAILERROR,
  SETALBUMLIST,
  SETALBUMLISTERROR,
  SETTRACKLIST,
  SETTRACKLISTERROR,
  SETTRACKITEM,
  SETTRACKITEMERROR
};
